version: 2

jobs:
  unit-test:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-modules-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - node-modules-

      - run:
        name: "Install global packages"
        command: |
          yarn global add truffle

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "yarn.lock" }}
        
      - run:
        name: "Compile contracts"
        command: |
          yarn build-contracts

      - run: yarn test

workflows:
  version: 2
  commit:
    jobs:
      - unit-test
